### ISSUE TITLE
Missing required architecture i386

### ISSUE THREAD

**Issue by dinarajas** [payu-intrepos/iOS-Custom-Browser#1]
> ld: warning: ignoring file /Users/DineshRaja/Documents/Projects/App-iOS/App-iOS/libiOSCustomBrowser.a, missing required architecture i386 in file /Users/DineshRaja/Documents/Projects/App-iOS/App-iOS/libiOSCustomBrowser.a (3 slices)
> Undefined symbols for architecture i386:
>   "_OBJC_CLASS_$_CBConnection", referenced from:
>       type metadata accessor for __ObjC.CBConnection in PayUWebViewController.o
> ld: symbol(s) not found for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm experiencing the above error and I couldn't run the app in simulators. It is because the binary is not included i386 architecture. Please help me.

**Comment by n4nachiket** [comment]
I have the same problem as @dineshrajas . Please help
