### ISSUE TITLE
iPad Only: Fatal Exception

### ISSUE THREAD

**Issue by Sandesh-Kumar** [payu-intrepos/iOS-Custom-Browser#11]
App is crashing when webpage is pushed with following log.

**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[PUCBWebVC webView:decidePolicyForNavigationAction:decisionHandler:] was not called'**

Note: This issue is only observed in iPad, in iPhone it is working fine.

**Comment by vipin04** [comment]
@Sandesh-Kumar : Which version of of Custom Browser are you using?

**Comment by Sandesh-Kumar** [comment]
@vipin04 I am using v5.8.3

**Comment by vipin04** [comment]
Thanks for reporting the issue. We will check it and get back to you by end of the day today.

**Comment by vipin04** [comment]
Issue has been identified and fixed. Fix will be available in next release recycle (5.9). If iPad is critical for your app, please raise this issue with your key accounts manager at PayU for prioritising this so that early release can be made.

**Comment by Sandesh-Kumar** [comment]
Thanks @vipin04, I will check the priority of this crash and contact Payu for point release if needed.

**Comment by amit-vivid** [comment]
@vipin04  We are also getting this crash for iPad users.
Using v5.8.3.
