### ISSUE TITLE
ITMS-90809: Deprecated UIWebView API Usage

### ISSUE THREAD

**Issue by Sandesh-Kumar** [payu-intrepos/iOS-Custom-Browser#12]
@vipin04 
Got the below warning while submitting the app to appstore.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Not sure whether the warning is due to usage of this SDK. If the warning is due to this SDK, can we expect a release with this fix?

**Comment by umangarya336** [comment]
Hi Sandesh,
Custom Browser without UIWebview is under testing with QA team.
Once it is tested we will release it soon.

**Comment by Sandesh-Kumar** [comment]
@umangarya336 Thanks, Hope you are including #11 issue too in the release.
