### ISSUE TITLE
iPad crash

### ISSUE THREAD

**Issue by amit-vivid** [payu-intrepos/iOS-Custom-Browser#13]
I am getting this crash for iPad users and using v5.8.3. Please check it and suggest a solution for it ASAP.
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[PUCBWebVC webView:decidePolicyForNavigationAction:decisionHandler:] was not called'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c4ee6c +[NSException raise:format:] + 188
	3   WebKit                              0x00007fff2d056dd1 _ZN6WebKit28CompletionHandlerCallCheckerD2Ev + 125
	4   WebKit                              0x00007fff2d48c193 _ZN3WTF3RefIN6WebKit28CompletionHandlerCallCheckerENS_13DumbPtrTraitsIS2_EEED2Ev + 27
	5   WebKit                              0x00007fff2d128698 _ZZN3WTF8BlockPtrIFv24WKNavigationActionPolicyEE12fromCallableIZN6WebKit15NavigationState16NavigationClient31decidePolicyForNavigationActionERNS5_12WebPageProxyEONS_3RefIN3API16NavigationActionENS_13DumbPtrTraitsISC_EEEEONSA_INS5_27WebFramePolicyListenerProxyENSD_ISH_EEEEPNSB_6ObjectEE3$_3EES3_T_ENUlPKvE_8__invokeESQ_ + 52
	6   libsystem_blocks.dylib              0x00007fff51a6f9c2 _Block_release + 101
	7   WebKit                              0x00007fff2d1223d9 _ZN6WebKit15NavigationState16NavigationClient31decidePolicyForNavigationActionERNS_12WebPageProxyEON3WTF3RefIN3API16NavigationActionENS4_13DumbPtrTraitsIS7_EEEEONS5_INS_27WebFramePolicyListenerProxyENS8_ISC_EEEEPNS6_6ObjectE + 1255
	8   WebKit                              0x00007fff2d16dba8 _ZN6WebKit12WebPageProxy31decidePolicyForNavigationActionEON3WTF3RefINS_15WebProcessProxyENS1_13DumbPtrTraitsIS3_EEEERNS_13WebFrameProxyEON7WebCore18SecurityOriginDataEyONS_20NavigationActionDataEONS_13FrameInfoDataENS1_8OptionalINS1_16ObjectIdentifierINSA_18PageIdentifierTypeEEEEERKNSA_15ResourceRequestEOSM_ON3IPC17FormDataReferenceEONSA_16ResourceResponseERKNS_8UserDataEONS2_INS0_20PolicyDecisionSenderENS4_ISY_EEEE + 2822
	9   WebKit                              0x00007fff2d16d044 _ZN6WebKit12WebPageProxy42decidePolicyForNavigationActionAsyncSharedEON3WTF3RefINS_15WebProcessProxyENS1_13DumbPtrTraitsIS3_EEEEyON7WebCore18SecurityOriginDataENS8_21PolicyCheckIdentifierEyONS_20NavigationActionDataEONS_13FrameInfoDataENS1_8OptionalINS1_16ObjectIdentifierINS8_18PageIdentifierTypeEEEEERKNS8_15ResourceRequestEOSL_ON3IPC17FormDataReferenceEONS8_16ResourceResponseERKNS_8UserDataEy + 412
	10  WebKit                              0x00007fff2d16ce77 _ZN6WebKit12WebPageProxy36decidePolicyForNavigationActionAsyncEyON7WebCore18SecurityOriginDataENS1_21PolicyCheckIdentifierEyONS_20NavigationActionDataEONS_13FrameInfoDataEN3WTF8OptionalINS9_16ObjectIdentifierINS1_18PageIdentifierTypeEEEEERKNS1_15ResourceRequestEOSF_ON3IPC17FormDataReferenceEONS1_16ResourceResponseERKNS_8UserDataEy + 133
	11  WebKit                              0x00007fff2d3e2f0d _ZN3IPC22callMemberFunctionImplIN6WebKit12WebPageProxyEMS2_FvyON7WebCore18SecurityOriginDataENS3_21PolicyCheckIdentifierEyONS1_20NavigationActionDataEONS1_13FrameInfoDataEN3WTF8OptionalINSB_16ObjectIdentifierINS3_18PageIdentifierTypeEEEEERKNS3_15ResourceRequestEOSH_ONS_17FormDataReferenceEONS3_16ResourceResponseERKNS1_8UserDataEyENSt3__15tupleIJyS4_S6_yS7_S9_SG_SH_SH_SL_SN_SP_yEEEJLm0ELm1ELm2ELm3ELm4ELm5ELm6ELm7ELm8ELm9ELm10ELm11ELm12EEEEvPT_T0_OT1_NSU_16integer_sequenceImJXspT2_EEEE + 173
	12  WebKit                              0x00007fff2d3d2f77 _ZN3IPC13handleMessageIN8Messages12WebPageProxy36DecidePolicyForNavigationActionAsyncEN6WebKit12WebPageProxyEMS5_FvyON7WebCore18SecurityOriginDataENS6_21PolicyCheckIdentifierEyONS4_20NavigationActionDataEONS4_13FrameInfoDataEN3WTF8OptionalINSE_16ObjectIdentifierINS6_18PageIdentifierTypeEEEEERKNS6_15ResourceRequestEOSK_ONS_17FormDataReferenceEONS6_16ResourceResponseERKNS4_8UserDataEyEEEvRNS_7DecoderEPT0_T1_ + 83
	13  WebKit                              0x00007fff2cf5926e _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 114
	14  WebKit                              0x00007fff2d1a3928 _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 24
	15  WebKit                              0x00007fff2cf44912 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 158
	16  WebKit                              0x00007fff2cf47664 _ZN3IPC10Connection24dispatchIncomingMessagesEv + 408
	17  JavaScriptCore                      0x00007fff26881d74 _ZN3WTF7RunLoop11performWorkEv + 228
	18  JavaScriptCore                      0x00007fff26882002 _ZN3WTF7RunLoop11performWorkEPv + 34
	19  CoreFoundation                      0x00007fff23bb2221 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	20  CoreFoundation                      0x00007fff23bb214c __CFRunLoopDoSource0 + 76
	21  CoreFoundation                      0x00007fff23bb1924 __CFRunLoopDoSources0 + 180
	22  CoreFoundation                      0x00007fff23bac62f __CFRunLoopRun + 1263
	23  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	24  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	25  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	27  libdyld.dylib                       0x00007fff51a1dc25 start + 1
	28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vipin04** [comment]
@umangarya336 - Can you look at it? I remember fixing this. It was due to an incorrect check of `UIUserInterfaceIdiomPhone`

**Comment by amit-vivid** [comment]
Can you please help for this fix?

**Comment by umangarya336** [comment]
@amit-vivid : I tried to debug it using Xcode version 11.3 but was not able to reproduce it. Please try our sample app https://github.com/payu-intrepos/iOS-SDK-Sample-App this app contains Custom browser.
If issue still exists please let us know.
