### ISSUE TITLE
Paytm Wallet transaction redirects to Paytm Native app rather than browser itself.

### ISSUE THREAD

**Issue by AbhishekTF2020** [payu-intrepos/iOS-Custom-Browser#16]
Can you check your wallet payment via Paytm. 
It redirects to native app in iOS and nothing happens. 
Can you check and update how we can avoid that???

**Comment by umangarya336** [comment]
We are working on it.

**Comment by umangarya336** [comment]
The issue is in the latest app of Paytm. Please ask your clients/customer to update their paytm app.

**Comment by AbhishekTF2020** [comment]
Yeah it's fine now Thanks :)
