### ISSUE TITLE
Production Env PayUBiz payment not working

### ISSUE THREAD

**Issue by pankajnegi1893** [payu-intrepos/iOS-Custom-Browser#17]
PayUBiz production env I am unable to do the Payment. It's asking my card information but after that payment is failing. I have integrate the PayUBiz in android also. But in android it's working fine. Only in iOS payment Issue coming. Can anyone have solution for this ?

**Comment by umangarya336** [comment]
Hi Pankaj,
Could you please share failure message?
Are you using any other framework other than CustomBrowser? If yes then share there detail as well.

**Comment by pankajnegi1893** [comment]
I am also using PayU_iOS_CoreSDK with CustomBrowser. with Test Env it's working. but when using Production env it's not working.


some time we are getting  below error :- 

![image](https://user-images.githubusercontent.com/49673803/94241611-7be0d000-ff32-11ea-9780-5c89b316fa10.png)

**Comment by umangarya336** [comment]
Screenshots seems to be of Android App. But concern you have raised for iOS.
Anyway, you can shoot us an email at mobile.integration@payu.in with framework version information.
We are happy to help you!!
